- name: Install Python packages
  apt:
    name: "{{ python_packages }}"
    state: latest

- name: Clone Git repository
  git:
    repo: "https://github.com/chandradeoarya/twoge"
    dest: "/home/ubuntu/twoge"
    clone: yes
    update: yes

- name: Create Python virtual environment
  command:
    cmd: python3 -m venv /home/ubuntu/twoge/venv
    creates: /home/ubuntu/twoge/venv

- name: Install requirements
  pip:
    requirements: /home/ubuntu/twoge/requirements.txt
    virtualenv: /home/ubuntu/twoge/venv
    virtualenv_command: python3 -m venv

- name: Create systemd service file for twoge
  template:
    src: twoge.service.j2
    dest: /etc/systemd/system/twoge.service
    mode: '0644'

- name: Reload systemd to read new twoge service
  systemd:
    daemon_reload: yes

- name: Enable and start twoge service
  systemd:
    name: twoge
    enabled: yes
    state: started