---
- name: Install Nginx
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: Copy Nginx configuration for Twoge
  template:
    src: twoge_nginx.conf.j2
    dest: /etc/nginx/sites-available/twoge.conf
  notify:
    - restart nginx

- name: Enable Twoge site
  file:
    src: /etc/nginx/sites-available/twoge.conf
    dest: /etc/nginx/sites-enabled/twoge.conf
    state: link
  notify:
    - restart nginx

- name: Remove default Nginx site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify:
    - restart nginx
